### ISSUE TITLE
Not credited for full donation purchase?

### ISSUE THREAD

**Issue by lordsarudon** [StarQuestMinecraft/StarQuestPublic#942]
I made a 50 dollar purchase in the donation store, but only received credit for a 20 dollar purchase. Is there any way to get the remaining credit on my character in the server? For example i should have the (III) donation indicator next to my name according to the store, but its only (II).

Minecraft username: Sard0n

**Comment by awangatboo** [comment]
Did you receive everything else it is just the (III) that is an (II) that should be fixed?

**Comment by lordsarudon** [comment]
When I use the /money command it tells me I have donated 20 dollars as well instead of 50, but the actual things I purchased are there

**Comment by awangatboo** [comment]
I have asked QuietHelper to look at this.  I really need to get his name on the list of people I can assign to.

**Comment by buba141** [comment]
The bug that caused this is fixed, but I can't credit the missing $30 for some reason. Have you changed your username recently?

**Comment by lordsarudon** [comment]
I did actually, new name is kromouroboros

**Comment by buba141** [comment]
That account already has $50 in donations, QuietHelper must have given you the missing donation credit.

**Comment by lordsarudon** [comment]
Is the $50 suposed to give a (III) donator tag? I noticed that I have the $50 now but I still have a (II) tag.
